Create new readme to proyect Adding new validation to ports

diff --git a/usr/bin/cimmyt-ggce-tool b/usr/bin/cimmyt-ggce-tool
--- a/usr/bin/cimmyt-ggce-tool
+++ b/usr/bin/cimmyt-ggce-tool
@@ -62,6 +62,12 @@ run_install() {
         exit 1
     fi
 
+    if ! environment::port_validation; then
+        ui::echo-message "Se deben liberar los puerto 3001, 3002, 1400 - para desplegar la aplicacion GGCE." "error"
+        exit 1
+    fi
+
+
     if ! confirm_clean_install; then
         exit 1
     fi
